### ISSUE TITLE
Unable to find a working version of Threejs to make this lib work

### ISSUE THREAD

**Issue by Sceat** [vberlier/three-mcmodel#163]
There is always a console error related three no matter which version i use :/ (even those in your package.json files)

**Comment by vberlier** [comment]
It worked at some point but I just never got around to do the necessary polish to make it usable and maintain it properly. So it's now been left to rot for years at this point. Looks like the last known working versions were `0.125.0` for `three` and `2.96.3` for `three-orbitcontrols`. But if you already tried that I honestly have no clue either.

**Comment by Sceat** [comment]
I managed to make [this fork](https://github.com/OrangeUtan/three-mcmodel) work! (which is unfortunately not listed as a fork) with an example of usage in his [vscode extension](https://github.com/OrangeUtan/vscode-mcmodel-viewer)

**Comment by vberlier** [comment]
Oh wow I didn't know this was based on `three-mcmodel`, that's really cool!
